spring:
  application:
    name: gatewayservice
  profiles:
    active: ${ACTIVE_PROFILE:local}
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    org:
      springframework:
        cloud:
          gateway=DEBUG: