spring:
  application:
    name: userservice
  profiles:
    active: ${ACTIVE_PROFILE:local}
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}

  jpa:
    show-sql: true
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server:
  port: ${SERVER_PORT:8100}

otel:
  traces:
    exporter: zipkin
  exporter:
    zipkin:
      endpoint: http://localhost:9411/api/v2/spans
  sdk:
    disabled: false