compose_up:
	docker-compose -f docker-compose-dev.yml up
elk_setup:
	docker-compose -f docker-compose-dev.yml up setup
elk_restart:
	docker-compose -f docker-compose-dev.yml restart elasticsearch kibana logstash